migration_storage:
  storage_type: "postgres"
  dsn: "postgres://postgres:postgres@db_cognition:5432/cognition?sslmode=disable"
  schema: "public"
  path: "data/migrations.db"

projects:
  project1:
    migrations:
    - postgres: ./migration
  
databases:
  postgres:
    type: postgres
    dsn: "postgres://postgres:postgres@db_cognition:5432/cognition?sslmode=disable"
    schema: "public"